[device]
#input = "Launchpad Pro MK3 LPProMK3 MIDI"
#output = "Launchpad Pro MK3 LPProMK3 MIDI"
lights = true

[mapping]
"A3" = "KeyW"
"E3" = "KeyA"
"F3" = "KeyS"
"F#3" = "KeyD"
"C6" = "KeyE"
"D6" = "KeyF"
"E5" = "Escape"

