[device]
#input = "Launchpad Pro MK3 LPProMK3 MIDI"
#output = "Launchpad Pro MK3 LPProMK3 MIDI"
lights = true

[mapping]
"A3" = { key = "KeyW" }
"E3" = { key = "KeyA" }
"F3" = { key = "KeyS" }
"F#3" = { key = "KeyD" }
"C6" = { key = "KeyE" }
"D6" = { key = "KeyF" }
"E5" = { key = "Escape" }
"F5" = { shell = { press = "ls" } }
"F#5" = { shell = { release = "ls" } }